#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - Enabling.md
  - Amplifiers.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

style: hacker
listen_for_clients_preferred_style: false

plugins:
  - jekyll-seo-tag
